name: VT Testing

on:
  - push

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run deno test script
        env:
          VAL_TOWN_API_KEY: ${{ secrets.VAL_TOWN_API_KEY }}
        run: deno task test:workflow

      - name: Run deno lint check
        run: deno task check

      - name: Run deno format check
        run: deno task fmt:check

  test-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run deno test
        env:
          VAL_TOWN_API_KEY: ${{ secrets.VAL_TOWN_API_KEY }}
        run: deno task test

  test-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Dry run publish package
        run: npx jsr publish --dry-run
