name: VT Testing

on:
  push:

env:
  CI: true

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run deno lint check
        run: deno task check

      - name: Run deno format check
        run: deno task fmt:check

      - name: Run deno tests
        uses: nick-fields/retry@v3
        with:
          command: deno task test:lib
          max_attempts: 2
          timeout_seconds: 2000
        env:
          VAL_TOWN_API_KEY: ${{ secrets.VAL_TOWN_API_KEY }}

  test-mac:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run deno tests
        uses: nick-fields/retry@v3
        with:
          command: deno task test:cmd
          max_attempts: 2
          timeout_seconds: 2000
        env:
          VAL_TOWN_API_KEY: ${{ secrets.VAL_TOWN_API_KEY_2 }}

  test-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
      - name: Dry run publish package
        run: npx jsr publish --dry-run
